version: '3.8'
services:
  commandsApp:
    image: facturedtest/commandapp
    build:
      context: .
      dockerfile: ./dockerfiles/commandapp.dockerfile      
    command: bash "/apps/commandApp/entrypoint.sh"
    ports:
      - 8000:8000
    volumes:
      - ./commandApp:/apps/commandApp
    environment:
      - TZ=America/El_Salvador
      - DB_NAME=facturedtest
      - DB_USER=facturedtest
      - DB_PASSWORD=facturedtest
      - DB_PORT=5432
    depends_on:
      - postgresqldbfr
    restart: unless-stopped
    

  postgresqldbfr:
    image: postgres:16.6-alpine3.21
    environment:
      POSTGRES_PASSWORD: facturedtest
      POSTGRES_USER: facturedtest
      POSTGRES_DB: facturedtest
    ports:
      - 5433:5432
#  querysApp:
#  apitGatewayAPP:
#  mongodb:
