# Generated by Django 4.2.17 on 2025-01-11 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tableros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('descripcion', models.CharField(max_length=500, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'TABLEROS',
            },
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, null=True)),
                ('descripcion', models.CharField(max_length=500, null=True)),
                ('estado', models.CharField(max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_tablero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.tableros')),
            ],
            options={
                'db_table': 'TAREAS',
            },
        ),
    ]
